name: Abstractly_alpha3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  http: ^0.13.6
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  clipboard: ^0.1.3
  flutter_tts: ^3.6.3
  share_plus: ^7.0.1
  translator: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
